import Image from "next/image";

export default function About() {
  return (
    <main className="flex min-h-screen flex-col items-center pt-12 p-6">
      <div className="w-full max-w-4xl">
        <h1 className="text-5xl font-bold mb-4 text-center">About ASCII Bench</h1>
        <div className="text-center mb-8">
          <pre className="text-3xl font-bold text-gray-800">
{`¯\\_(ツ)_/¯`}
          </pre>
        </div>
        
        {/* Overview Section */}
        <div className="bg-white border-2 border-gray-300 rounded-lg p-8 mb-8">
          <h2 className="text-2xl font-semibold mb-4">What is ASCII Bench?</h2>
          <p className="text-lg text-gray-700 leading-relaxed mb-4">
            ASCII Bench is an A/B voting platform designed to evaluate and compare the quality 
            of ASCII art generated by different AI models. Users are presented with pairs of 
            ASCII art outputs created from the same prompt and vote for the one they prefer.
          </p>
          <p className="text-lg text-gray-700 leading-relaxed">
            Through community voting, we build a leaderboard that ranks which AI models produce 
            the best ASCII art. This helps researchers and developers understand model capabilities 
            in creative text-based visual generation.
          </p>
        </div>

        {/* ELO Section */}
        <div className="bg-white border-2 border-gray-300 rounded-lg p-8 mb-8">
          <h2 className="text-2xl font-semibold mb-4">How do rankings work?</h2>
          <p className="text-lg text-gray-700 leading-relaxed mb-4">
            Each AI model has a single ELO rating that represents its overall performance across votes.
            When you pick a winner in a head‑to‑head matchup, the winner gains points and the loser loses points
            based on how expected the outcome was.
          </p>
          <p className="text-lg text-gray-700 leading-relaxed">
            We use a dynamic K‑factor: new models start with larger rating changes so they find their true level quickly,
            and as a model accumulates votes the changes shrink to keep the leaderboard stable.
          </p>
        </div>

        {/* Creator Section */}
        <div className="bg-white border-2 border-gray-300 rounded-lg p-8">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Jason */}
            <div className="flex flex-col items-center">
              <h2 className="text-xl font-semibold mb-2 text-black">Creator</h2>
              <pre className="text-2xl mb-4 text-gray-800">
{`( ͡° ͜ʖ ͡°)`}
              </pre>
              <div className="mb-4 relative w-32 h-32 rounded-full overflow-hidden border-4 border-gray-300">
                <Image
                  src="/JB.jpg"
                  alt="Jason Botterill"
                  fill
                  className="object-cover"
                />
              </div>
              <p className="text-xl font-semibold mb-2">Jason Botterill</p>
            </div>

            {/* Chris */}
            <div className="flex flex-col items-center">
              <h2 className="text-xl font-semibold mb-2 text-black">Owns 10%</h2>
              <pre className="text-2xl mb-4 text-gray-800">
{`( ͡ಠ ͜ʖ ͡ಠ)`}
              </pre>
              <div className="mb-4 relative w-32 h-32 rounded-full overflow-hidden border-4 border-gray-300">
                <Image
                  src="/chris.jpg"
                  alt="Chris"
                  fill
                  className="object-cover"
                />
              </div>
              <p className="text-xl font-semibold mb-2">Chris</p>
            </div>

            {/* Angel */}
            <div className="flex flex-col items-center">
              <h2 className="text-xl font-semibold mb-2 text-black">Contributor</h2>
              <pre className="text-2xl mb-4 text-gray-800">
{`(づ｡◕‿‿◕｡)づ`}
              </pre>
              <div className="mb-4 relative w-32 h-32 rounded-full overflow-hidden border-4 border-gray-300">
                <Image
                  src="/angel.jpg"
                  alt="Angel"
                  fill
                  className="object-cover"
                />
              </div>
              <p className="text-xl font-semibold mb-2">Angel</p>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
